"""Inicio Supabase

Revision ID: 3ab070b74889
Revises: 
Create Date: 2025-12-08 20:09:35.785899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab070b74889'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acad_aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('cor_raca', sa.String(length=50), nullable=True),
    sa.Column('filiacao_1', sa.String(length=200), nullable=True),
    sa.Column('filiacao_2', sa.String(length=200), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('id_inep', sa.String(length=20), nullable=True),
    sa.Column('nome_responsavel', sa.String(length=200), nullable=True),
    sa.Column('telefone_responsavel', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('necessidade_especial', sa.Boolean(), nullable=True),
    sa.Column('tipo_necessidade', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_inep')
    )
    with op.batch_alter_table('acad_aluno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acad_aluno_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_acad_aluno_nome_completo'), ['nome_completo'], unique=False)

    op.create_table('acad_disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('area_conhecimento', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('acad_periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acad_periodo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acad_periodo_ano_letivo'), ['ano_letivo'], unique=False)

    op.create_table('almox_fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('dados_bancarios', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('fiscal_checklist_modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo_contrato_associado', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('renewal_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('renewal_key')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_vinculo', sa.String(length=50), nullable=True),
    sa.Column('secretaria', sa.String(length=150), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('endereco', sa.String(length=250), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cnh_numero', sa.String(length=20), nullable=True),
    sa.Column('cnh_categoria', sa.String(length=5), nullable=True),
    sa.Column('cnh_validade', sa.Date(), nullable=True),
    sa.Column('rota_descricao', sa.String(length=300), nullable=True),
    sa.Column('turno', sa.String(length=50), nullable=True),
    sa.Column('veiculo_modelo', sa.String(length=100), nullable=True),
    sa.Column('veiculo_ano', sa.Integer(), nullable=True),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('pnae_agricultor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_fornecedor', sa.String(length=50), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('dap_caf_numero', sa.String(length=50), nullable=True),
    sa.Column('dap_caf_tipo', sa.String(length=50), nullable=True),
    sa.Column('dap_caf_validade', sa.Date(), nullable=True),
    sa.Column('representante_nome', sa.String(length=200), nullable=True),
    sa.Column('representante_rg', sa.String(length=20), nullable=True),
    sa.Column('representante_rg_orgao', sa.String(length=20), nullable=True),
    sa.Column('representante_rg_emissao', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco_completo', sa.String(length=300), nullable=True),
    sa.Column('zona', sa.String(length=20), nullable=True),
    sa.Column('comunidade', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('descricao_propriedade', sa.Text(), nullable=True),
    sa.Column('area_total_ha', sa.Float(), nullable=True),
    sa.Column('frequencia_entrega', sa.String(length=100), nullable=True),
    sa.Column('dias_horarios', sa.String(length=200), nullable=True),
    sa.Column('possui_transporte', sa.Boolean(), nullable=True),
    sa.Column('responsavel_entrega', sa.String(length=150), nullable=True),
    sa.Column('local_entrega_preferencia', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('pnae_configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('valor_total_repasse', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano')
    )
    op.create_table('produto_merenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('estoque_atual', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('protocolo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_protocolo', sa.String(length=20), nullable=False),
    sa.Column('assunto', sa.String(length=300), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('interessado', sa.String(length=200), nullable=False),
    sa.Column('setor_origem', sa.String(length=150), nullable=False),
    sa.Column('setor_atual', sa.String(length=150), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_protocolo')
    )
    op.create_table('secretaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('almox_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('estoque_atual', sa.Float(), nullable=False),
    sa.Column('estoque_minimo', sa.Float(), nullable=True),
    sa.Column('estoque_maximo', sa.Float(), nullable=True),
    sa.Column('localizacao_fisica', sa.String(length=100), nullable=True),
    sa.Column('ultimo_custo', sa.Float(), nullable=True),
    sa.Column('codigo_barras', sa.String(length=100), nullable=True),
    sa.Column('fornecedor_padrao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_padrao_id'], ['almox_fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras'),
    sa.UniqueConstraint('codigo_interno')
    )
    op.create_table('anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caee_aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('escola_origem', sa.String(length=200), nullable=True),
    sa.Column('cid_diagnostico', sa.String(length=20), nullable=True),
    sa.Column('necessidade_especifica', sa.String(length=200), nullable=True),
    sa.Column('nome_responsavel', sa.String(length=200), nullable=False),
    sa.Column('telefone_responsavel', sa.String(length=20), nullable=False),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('anamnese', sa.Text(), nullable=True),
    sa.Column('hipotese_diagnostica', sa.Text(), nullable=True),
    sa.Column('secretaria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['secretaria_id'], ['secretaria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caee_aluno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caee_aluno_cid_diagnostico'), ['cid_diagnostico'], unique=False)
        batch_op.create_index(batch_op.f('ix_caee_aluno_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_caee_aluno_nome_completo'), ['nome_completo'], unique=False)

    op.create_table('caee_profissional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('registro_conselho', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('secretaria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['secretaria_id'], ['secretaria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caee_profissional', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caee_profissional_cpf'), ['cpf'], unique=True)

    op.create_table('documento_motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscal_checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('tipo_resposta', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['fiscal_checklist_modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscal_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_contrato', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('processo_licitatorio', sa.String(length=150), nullable=True),
    sa.Column('empresa_contratada', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('representante_empresa', sa.String(length=150), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('valor_mensal_parcela', sa.Float(), nullable=True),
    sa.Column('vigencia_inicio', sa.Date(), nullable=False),
    sa.Column('vigencia_fim', sa.Date(), nullable=False),
    sa.Column('situacao', sa.String(length=50), nullable=False),
    sa.Column('secretaria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['secretaria_id'], ['secretaria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_contrato')
    )
    op.create_table('pnae_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agricultor_id', sa.Integer(), nullable=False),
    sa.Column('numero_contrato', sa.String(length=50), nullable=False),
    sa.Column('chamada_publica', sa.String(length=100), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_termino', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agricultor_id'], ['pnae_agricultor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pnae_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agricultor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('numero_ref', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agricultor_id'], ['pnae_agricultor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servidor',
    sa.Column('num_contrato', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('nome_mae', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('pis_pasep', sa.String(length=20), nullable=True),
    sa.Column('tipo_vinculo', sa.String(length=50), nullable=True),
    sa.Column('local_trabalho', sa.String(length=150), nullable=True),
    sa.Column('classe_nivel', sa.String(length=50), nullable=True),
    sa.Column('num_contra_cheque', sa.String(length=50), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=250), nullable=True),
    sa.Column('funcao', sa.String(length=100), nullable=True),
    sa.Column('lotacao', sa.String(length=100), nullable=True),
    sa.Column('carga_horaria', sa.String(length=50), nullable=True),
    sa.Column('remuneracao', sa.Float(), nullable=True),
    sa.Column('dados_bancarios', sa.String(length=200), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto_filename', sa.String(length=100), nullable=True),
    sa.Column('face_encoding', sa.Text(), nullable=True),
    sa.Column('num_contrato_gerado', sa.String(length=10), nullable=True),
    sa.Column('secretaria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['secretaria_id'], ['secretaria.id'], ),
    sa.PrimaryKeyConstraint('num_contrato'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('num_contrato_gerado')
    )
    op.create_table('tramitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo_id', sa.Integer(), nullable=False),
    sa.Column('setor_origem', sa.String(length=150), nullable=False),
    sa.Column('setor_destino', sa.String(length=150), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('despacho', sa.Text(), nullable=True),
    sa.Column('usuario_responsavel', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('secretaria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['secretaria_id'], ['secretaria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('veiculo',
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=True),
    sa.Column('ano_modelo', sa.Integer(), nullable=True),
    sa.Column('orgao', sa.String(length=150), nullable=True),
    sa.Column('secretaria_id', sa.Integer(), nullable=False),
    sa.Column('autorizacao_detran', sa.String(length=50), nullable=True),
    sa.Column('validade_autorizacao', sa.Date(), nullable=True),
    sa.Column('renavam', sa.String(length=50), nullable=True),
    sa.Column('certificado_tacografo', sa.String(length=50), nullable=True),
    sa.Column('data_emissao_tacografo', sa.Date(), nullable=True),
    sa.Column('validade_tacografo', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['secretaria_id'], ['secretaria.id'], ),
    sa.PrimaryKeyConstraint('placa')
    )
    op.create_table('abastecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('quilometragem', sa.Float(), nullable=False),
    sa.Column('tipo_combustivel', sa.String(length=50), nullable=False),
    sa.Column('litros', sa.Float(), nullable=False),
    sa.Column('valor_litro', sa.Float(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.ForeignKeyConstraint(['veiculo_placa'], ['veiculo.placa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('almox_requisicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('secretaria_solicitante_id', sa.Integer(), nullable=False),
    sa.Column('usuario_solicitante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['secretaria_solicitante_id'], ['secretaria.id'], ),
    sa.ForeignKeyConstraint(['usuario_solicitante_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caee_laudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('filename_seguro', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=False),
    sa.Column('uploader_nome', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['caee_aluno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caee_linha_tempo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('profissional_origem_id', sa.Integer(), nullable=True),
    sa.Column('profissional_destino_id', sa.Integer(), nullable=True),
    sa.Column('etapa', sa.String(length=100), nullable=False),
    sa.Column('data_evento', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['caee_aluno.id'], ),
    sa.ForeignKeyConstraint(['profissional_destino_id'], ['caee_profissional.id'], ),
    sa.ForeignKeyConstraint(['profissional_origem_id'], ['caee_profissional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caee_plano_atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('status_plano', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('frequencia_semanal', sa.Integer(), nullable=True),
    sa.Column('duracao_sessao_min', sa.Integer(), nullable=True),
    sa.Column('objetivos_gerais', sa.Text(), nullable=True),
    sa.Column('objetivos_especificos', sa.Text(), nullable=True),
    sa.Column('metodologia', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['caee_aluno.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['caee_profissional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caee_relatorio_periodico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('data_relatorio', sa.DateTime(), nullable=True),
    sa.Column('relatorio_evolucao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['caee_aluno.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['caee_profissional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('servidor_cpf', sa.String(length=14), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('assinatura_secretaria_tipo', sa.String(length=20), nullable=True),
    sa.Column('assinatura_secretaria_dados', sa.String(length=255), nullable=True),
    sa.Column('data_geracao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['servidor_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('servidor_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidor.num_contrato'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_assinado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_documento', sa.String(length=300), nullable=False),
    sa.Column('codigo_validade', sa.String(length=100), nullable=False),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.Column('filename_seguro', sa.String(length=300), nullable=True),
    sa.Column('servidor_cpf', sa.String(length=14), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=True),
    sa.Column('pos_y', sa.Float(), nullable=True),
    sa.Column('pagina', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['servidor_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_validade')
    )
    op.create_table('escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('codigo_inep', sa.String(length=8), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('diretor_cpf', sa.String(length=14), nullable=True),
    sa.Column('responsavel_merenda_cpf', sa.String(length=14), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['diretor_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['responsavel_merenda_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('escola', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escola_codigo_inep'), ['codigo_inep'], unique=True)

    op.create_table('fiscal_anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('filename_seguro', sa.String(length=255), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['fiscal_contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscal_atesto_mensal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('mes_competencia', sa.String(length=7), nullable=False),
    sa.Column('data_atesto', sa.DateTime(), nullable=True),
    sa.Column('descricao_servico', sa.Text(), nullable=False),
    sa.Column('conformidade', sa.String(length=50), nullable=False),
    sa.Column('observacoes_fiscal', sa.Text(), nullable=True),
    sa.Column('evidencia_filename', sa.String(length=255), nullable=True),
    sa.Column('localizacao_gps', sa.String(length=100), nullable=True),
    sa.Column('assinatura_fiscal', sa.String(length=100), nullable=False),
    sa.Column('status_atesto', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['fiscal_contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscal_ocorrencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ocorrencia', sa.String(length=100), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('descricao_detalhada', sa.Text(), nullable=False),
    sa.Column('gravidade', sa.String(length=50), nullable=False),
    sa.Column('evidencia_filename', sa.String(length=255), nullable=True),
    sa.Column('local_ocorrencia', sa.String(length=200), nullable=True),
    sa.Column('responsavel_registro', sa.String(length=100), nullable=False),
    sa.Column('responsavel_analise', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['fiscal_contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_num_contrato', sa.String(length=50), nullable=False),
    sa.Column('texto_inicial_observacoes', sa.Text(), nullable=True),
    sa.Column('data_laudo', sa.Date(), nullable=True),
    sa.Column('medico_laudo', sa.String(length=200), nullable=True),
    sa.Column('dias_afastamento_laudo', sa.Integer(), nullable=True),
    sa.Column('justificativa_laudo', sa.Text(), nullable=True),
    sa.Column('cid10', sa.String(length=20), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['servidor_num_contrato'], ['servidor.num_contrato'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manutencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('quilometragem', sa.Float(), nullable=False),
    sa.Column('tipo_servico', sa.String(length=150), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('oficina', sa.String(length=150), nullable=True),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['veiculo_placa'], ['veiculo.placa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patrimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_patrimonio', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('localizacao', sa.String(length=200), nullable=False),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('valor_aquisicao', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('servidor_responsavel_cpf', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['servidor_responsavel_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_patrimonio')
    )
    op.create_table('pnae_entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=False),
    sa.Column('numero_nota_fiscal', sa.String(length=50), nullable=True),
    sa.Column('recibo_filename', sa.String(length=255), nullable=True),
    sa.Column('responsavel_recebimento', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('itens_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['pnae_contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pnae_item_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('unidade_medida', sa.String(length=20), nullable=True),
    sa.Column('quantidade_total', sa.Float(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('tipo_producao', sa.String(length=50), nullable=True),
    sa.Column('sazonalidade', sa.String(length=200), nullable=True),
    sa.Column('periodicidade', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['pnae_contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requerimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autoridade_dirigida', sa.String(length=200), nullable=False),
    sa.Column('servidor_cpf', sa.String(length=14), nullable=False),
    sa.Column('natureza', sa.String(length=100), nullable=False),
    sa.Column('natureza_outro', sa.String(length=255), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_inicio_requerimento', sa.Date(), nullable=False),
    sa.Column('duracao', sa.String(length=50), nullable=True),
    sa.Column('periodo_aquisitivo', sa.String(length=20), nullable=True),
    sa.Column('data_retorno_trabalho', sa.Date(), nullable=True),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.Column('informacoes_complementares', sa.Text(), nullable=True),
    sa.Column('parecer_juridico', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['servidor_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rota_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motorista_cpf', sa.String(length=14), nullable=False),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=False),
    sa.Column('monitor_cpf', sa.String(length=14), nullable=True),
    sa.Column('escolas_manha', sa.String(length=500), nullable=True),
    sa.Column('itinerario_manha', sa.Text(), nullable=True),
    sa.Column('qtd_alunos_manha', sa.Integer(), nullable=True),
    sa.Column('coordenadas_manha', sa.Text(), nullable=True),
    sa.Column('escolas_tarde', sa.String(length=500), nullable=True),
    sa.Column('itinerario_tarde', sa.Text(), nullable=True),
    sa.Column('qtd_alunos_tarde', sa.Integer(), nullable=True),
    sa.Column('coordenadas_tarde', sa.Text(), nullable=True),
    sa.Column('horario_saida_manha', sa.Time(), nullable=True),
    sa.Column('horario_volta_manha', sa.Time(), nullable=True),
    sa.Column('horario_saida_tarde', sa.Time(), nullable=True),
    sa.Column('horario_volta_tarde', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['monitor_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['motorista_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['veiculo_placa'], ['veiculo.placa'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acad_turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(length=50), nullable=False),
    sa.Column('etapa_ensino', sa.String(length=100), nullable=False),
    sa.Column('modalidade', sa.String(length=100), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('almox_requisicao_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade_solicitada', sa.Float(), nullable=False),
    sa.Column('quantidade_atendida', sa.Float(), nullable=True),
    sa.Column('requisicao_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['almox_material.id'], ),
    sa.ForeignKeyConstraint(['requisicao_id'], ['almox_requisicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('ano_estudo', sa.String(length=50), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('escola', sa.String(length=200), nullable=False),
    sa.Column('zona', sa.String(length=20), nullable=False),
    sa.Column('nome_responsavel', sa.String(length=200), nullable=False),
    sa.Column('telefone_responsavel', sa.String(length=20), nullable=False),
    sa.Column('endereco_aluno', sa.String(length=300), nullable=False),
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('nivel_ensino', sa.String(length=100), nullable=True),
    sa.Column('possui_deficiencia', sa.Boolean(), nullable=True),
    sa.Column('tipo_deficiencia', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['rota_id'], ['rota_transporte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caee_sessao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('data_sessao', sa.DateTime(), nullable=False),
    sa.Column('presenca', sa.Boolean(), nullable=False),
    sa.Column('atividades_realizadas', sa.Text(), nullable=True),
    sa.Column('observacoes_evolucao', sa.Text(), nullable=True),
    sa.Column('profissional_nome', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['caee_plano_atendimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('escola_id', 'mes', 'ano', name='_escola_mes_ano_uc')
    )
    op.create_table('fiscal_checklist_resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atesto_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('valor_resposta', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['atesto_id'], ['fiscal_atesto_mensal.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['fiscal_checklist_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscal_nota_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('numero_nf', sa.String(length=100), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('atesto_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('usuario_registro', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['atesto_id'], ['fiscal_atesto_mensal.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['fiscal_contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiscal_penalidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocorrencia_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('base_legal', sa.String(length=200), nullable=True),
    sa.Column('descricao_infracao', sa.Text(), nullable=False),
    sa.Column('valor_multa', sa.Float(), nullable=True),
    sa.Column('data_aplicacao', sa.Date(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=False),
    sa.Column('documento_gerado', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['fiscal_ocorrencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacao_patrimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patrimonio_id', sa.Integer(), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=False),
    sa.Column('local_origem', sa.String(length=200), nullable=False),
    sa.Column('responsavel_anterior_cpf', sa.String(length=14), nullable=True),
    sa.Column('local_destino', sa.String(length=200), nullable=False),
    sa.Column('responsavel_novo_cpf', sa.String(length=14), nullable=True),
    sa.Column('usuario_registro', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['patrimonio_id'], ['patrimonio.id'], ),
    sa.ForeignKeyConstraint(['responsavel_anterior_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['responsavel_novo_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servidor_cpf', sa.String(length=14), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('foto_filename', sa.String(length=100), nullable=True),
    sa.Column('escola_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.ForeignKeyConstraint(['servidor_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_merenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('solicitante_cpf', sa.String(length=14), nullable=False),
    sa.Column('autorizador_cpf', sa.String(length=14), nullable=True),
    sa.Column('entregador_cpf', sa.String(length=14), nullable=True),
    sa.ForeignKeyConstraint(['autorizador_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['entregador_cpf'], ['servidor.cpf'], ),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], ),
    sa.ForeignKeyConstraint(['solicitante_cpf'], ['servidor.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trecho_rota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('tipo_viagem', sa.String(length=10), nullable=False),
    sa.Column('distancia_km', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['rota_id'], ['rota_transporte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acad_matricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_matricula', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['acad_aluno.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['acad_turma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acad_turma_disciplinas_professores',
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('professor_num_contrato', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['acad_disciplina.id'], ),
    sa.ForeignKeyConstraint(['professor_num_contrato'], ['servidor.num_contrato'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['acad_turma.id'], ),
    sa.PrimaryKeyConstraint('turma_id', 'disciplina_id', 'professor_num_contrato')
    )
    op.create_table('almox_movimento_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_movimento', sa.DateTime(), nullable=False),
    sa.Column('tipo_movimento', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('nota_fiscal', sa.String(length=100), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('requisicao_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['almox_fornecedor.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['almox_material.id'], ),
    sa.ForeignKeyConstraint(['requisicao_item_id'], ['almox_requisicao_item.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque_movimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('data_movimento', sa.DateTime(), nullable=True),
    sa.Column('fornecedor', sa.String(length=200), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('solicitacao_id', sa.Integer(), nullable=True),
    sa.Column('usuario_responsavel', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto_merenda.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacao_merenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_cardapio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardapio_id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('data_modificacao', sa.DateTime(), nullable=True),
    sa.Column('descricao_mudanca', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cardapio_id'], ['cardapio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prato_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardapio_id', sa.Integer(), nullable=False),
    sa.Column('data_prato', sa.Date(), nullable=False),
    sa.Column('nome_prato', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['cardapio_id'], ['cardapio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_merenda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_solicitada', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto_merenda.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_merenda_id'], ['solicitacao_merenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acad_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('professor_num_contrato', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['acad_disciplina.id'], ),
    sa.ForeignKeyConstraint(['matricula_id'], ['acad_matricula.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['acad_periodo.id'], ),
    sa.ForeignKeyConstraint(['professor_num_contrato'], ['servidor.num_contrato'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula_id', 'disciplina_id', 'periodo_id', name='_nota_unica_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acad_nota')
    op.drop_table('solicitacao_item')
    op.drop_table('prato_diario')
    op.drop_table('historico_cardapio')
    op.drop_table('estoque_movimento')
    op.drop_table('almox_movimento_estoque')
    op.drop_table('acad_turma_disciplinas_professores')
    op.drop_table('acad_matricula')
    op.drop_table('trecho_rota')
    op.drop_table('solicitacao_merenda')
    op.drop_table('ponto')
    op.drop_table('movimentacao_patrimonio')
    op.drop_table('fiscal_penalidade')
    op.drop_table('fiscal_nota_fiscal')
    op.drop_table('fiscal_checklist_resposta')
    op.drop_table('cardapio')
    op.drop_table('caee_sessao')
    op.drop_table('aluno_transporte')
    op.drop_table('almox_requisicao_item')
    op.drop_table('acad_turma')
    op.drop_table('rota_transporte')
    op.drop_table('requerimento')
    op.drop_table('pnae_item_projeto')
    op.drop_table('pnae_entrega')
    op.drop_table('patrimonio')
    op.drop_table('nota')
    op.drop_table('manutencao')
    op.drop_table('gam')
    op.drop_table('fiscal_ocorrencia')
    op.drop_table('fiscal_atesto_mensal')
    op.drop_table('fiscal_anexo')
    with op.batch_alter_table('escola', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escola_codigo_inep'))

    op.drop_table('escola')
    op.drop_table('documento_assinado')
    op.drop_table('documento')
    op.drop_table('contrato')
    op.drop_table('caee_relatorio_periodico')
    op.drop_table('caee_plano_atendimento')
    op.drop_table('caee_linha_tempo')
    op.drop_table('caee_laudo')
    op.drop_table('almox_requisicao')
    op.drop_table('abastecimento')
    op.drop_table('veiculo')
    op.drop_table('user')
    op.drop_table('tramitacao')
    op.drop_table('servidor')
    op.drop_table('pnae_documento')
    op.drop_table('pnae_contrato')
    op.drop_table('fiscal_contrato')
    op.drop_table('fiscal_checklist_item')
    op.drop_table('documento_motorista')
    with op.batch_alter_table('caee_profissional', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caee_profissional_cpf'))

    op.drop_table('caee_profissional')
    with op.batch_alter_table('caee_aluno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caee_aluno_nome_completo'))
        batch_op.drop_index(batch_op.f('ix_caee_aluno_cpf'))
        batch_op.drop_index(batch_op.f('ix_caee_aluno_cid_diagnostico'))

    op.drop_table('caee_aluno')
    op.drop_table('anexo')
    op.drop_table('almox_material')
    op.drop_table('secretaria')
    op.drop_table('protocolo')
    op.drop_table('produto_merenda')
    op.drop_table('pnae_configuracao')
    op.drop_table('pnae_agricultor')
    op.drop_table('motorista')
    op.drop_table('log')
    op.drop_table('license')
    op.drop_table('fiscal_checklist_modelo')
    op.drop_table('almox_fornecedor')
    with op.batch_alter_table('acad_periodo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acad_periodo_ano_letivo'))

    op.drop_table('acad_periodo')
    op.drop_table('acad_disciplina')
    with op.batch_alter_table('acad_aluno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acad_aluno_nome_completo'))
        batch_op.drop_index(batch_op.f('ix_acad_aluno_cpf'))

    op.drop_table('acad_aluno')
    # ### end Alembic commands ###
