"""Aplica restrições unique e not-null ao email

Revision ID: 69104bd19348
Revises: (algum_id_anterior)
Create Date: (alguma_data)

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69104bd19348'
down_revision = '20e2cf6b0667' # Mantenha o que estava aqui
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        
        # --- CORREÇÃO AQUI ---
        # Trocamos 'None' por um nome de restrição, como "uq_user_email"
        batch_op.create_unique_constraint("uq_user_email", ['email'])
        # -------------------

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        
        # --- CORREÇÃO AQUI ---
        # Trocamos 'None' pelo mesmo nome de restrição
        batch_op.drop_constraint("uq_user_email", type_='unique')
        # -------------------
        
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###