"""Adiciona diario de classe e corrige FK de professor

Revision ID: 6c430cc5f87b
Revises: a5d9d8a101c0
Create Date: 2025-10-14 14:41:37.801241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c430cc5f87b'
down_revision = 'a5d9d8a101c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acad_disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('area_conhecimento', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('acad_periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ano_letivo', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acad_periodo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acad_periodo_ano_letivo'), ['ano_letivo'], unique=False)

    op.create_table('acad_turma_disciplinas_professores',
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('professor_num_contrato', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['acad_disciplina.id'], ),
    sa.ForeignKeyConstraint(['professor_num_contrato'], ['servidor.num_contrato'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['acad_turma.id'], ),
    sa.PrimaryKeyConstraint('turma_id', 'disciplina_id', 'professor_num_contrato')
    )
    op.create_table('acad_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('matricula_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('professor_num_contrato', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['acad_disciplina.id'], ),
    sa.ForeignKeyConstraint(['matricula_id'], ['acad_matricula.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['acad_periodo.id'], ),
    sa.ForeignKeyConstraint(['professor_num_contrato'], ['servidor.num_contrato'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula_id', 'disciplina_id', 'periodo_id', name='_nota_unica_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acad_nota')
    op.drop_table('acad_turma_disciplinas_professores')
    with op.batch_alter_table('acad_periodo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acad_periodo_ano_letivo'))

    op.drop_table('acad_periodo')
    op.drop_table('acad_disciplina')
    # ### end Alembic commands ###
