"""Adiciona configuracao financeira PNAE

Revision ID: a0439acee63f
Revises: 0016f7e3468b
Create Date: 2025-12-03 18:47:32.686901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0439acee63f'
down_revision = '0016f7e3468b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnae_configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('valor_total_repasse', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pnae_configuracao')
    # ### end Alembic commands ###
